// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfCA_IYTCXn0mk8-HTcJjtPjnAcT6rLqY',
    appId: '1:1035957605024:web:32625f43f5858fb12f2fc5',
    messagingSenderId: '1035957605024',
    projectId: 'assignment-reminder-app',
    authDomain: 'assignment-reminder-app.firebaseapp.com',
    storageBucket: 'assignment-reminder-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVALLCZzLAG61rKLZGMtCHV7a4j5-RGos',
    appId: '1:1035957605024:android:cad785c50c8b022b2f2fc5',
    messagingSenderId: '1035957605024',
    projectId: 'assignment-reminder-app',
    storageBucket: 'assignment-reminder-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GvAasW44KBl-uv5P6MBfEvXZ6F6B1QU',
    appId: '1:1035957605024:ios:f2ab8226b808f99e2f2fc5',
    messagingSenderId: '1035957605024',
    projectId: 'assignment-reminder-app',
    storageBucket: 'assignment-reminder-app.firebasestorage.app',
    iosBundleId: 'com.example.assignmentReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6GvAasW44KBl-uv5P6MBfEvXZ6F6B1QU',
    appId: '1:1035957605024:ios:f2ab8226b808f99e2f2fc5',
    messagingSenderId: '1035957605024',
    projectId: 'assignment-reminder-app',
    storageBucket: 'assignment-reminder-app.firebasestorage.app',
    iosBundleId: 'com.example.assignmentReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfCA_IYTCXn0mk8-HTcJjtPjnAcT6rLqY',
    appId: '1:1035957605024:web:07f1d1b7d22e5a892f2fc5',
    messagingSenderId: '1035957605024',
    projectId: 'assignment-reminder-app',
    authDomain: 'assignment-reminder-app.firebaseapp.com',
    storageBucket: 'assignment-reminder-app.firebasestorage.app',
  );
}
